version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot"]
