dist: xenial
language: generic
addons:
  snaps:
  - name: hugo
    channel: extended
script:
- hugo --minify
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  fqdn: cata.ttp.sh
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: pwRVZJ3YQHoLQoFDyStv6Z1ASoAMk8ei1Xe7cGBsjDVaeelHKI8sCvKhylKFWWnKdfc8C0LxK7fxvAjSwjnamRfVI4K/YIL9hOv0W52QIh76A3eD8BB3luGqwjhUX2Qt+ZvwyqDQvZ9n+72LFU8FLNdGFbq3uco5Y2D3A9oI5w+u3BlbQDgy/IhOWiVHIeXXn3aCCM+iwmMWx3KTLSaFcDsco1X6GL4/QO4gYb7CeRLtKD++2uJVagtymZ28Nd2JHcq01deEiWjSMmReRDAk1kKFf0//nUiN+80mNkNd0PUq0F/kLDjEmP9qaM0NneWUH3zJBZIHNAb4OAnwgxMbKygE2IGAnuYK7wm0uX9A21Mcv7RwqIEnPbul/Ne6/3+BDk+PIrsH4ce480XnFafQ2zMTBbNE1vwx9gAdu58bsh7SkyDLnmAp6xHmfubgtdWTcXS6Z1LDRfUUaevrP8zyc5oy8zSvj4rSvurIBfotSGPyHfVqPMe5T0EL4G98Bftl7mJ2kisz6QgbmWaq56FmsE1D5ni5D/7EgzP5v9yKaYNEJwlQNrUEkTDQHFJSpq14zLt/bI+ZOZgt5RZ3K4SrFWvgjwzvfTx3F78oO4tfgVf0dMrHGoJ7lVt/uARCpCIKOB/1k1ySpmG/kOtW9Z5CzTCvbxjDpyQ0Hb+y02Uycok=
